### Create Product

POST http://localhost:8080/odata/v4/AdminService/Products
Content-Type: application/json

{
    "ID": 42, 
    "title": "My Tutorial Product", 
    "descr": "You are doing an awesome job!"
}

### Read Product

GET http://localhost:8080/odata/v4/AdminService/Products
Content-Type: application/json

### Create Categories

POST http://localhost:8080/odata/v4/AdminService/Categories
Content-Type: application/json

{"ID": 1, "name": "TechEd", "descr": "TechEd related topics", "children": [{"ID": 10, "name": "CAP Java", "descr": "Run on Java"}, {"ID": 11, "name": "CAP Node.js", "descr": "Run on Node.js"}]}

### Read Categories

GET http://localhost:8080/odata/v4/AdminService/Categories
Content-Type: application/json

### Read Categories

GET http://localhost:8080/odata/v4/AdminService/Categories(10)
Content-Type: application/json

### Read Categories

GET http://localhost:8080/odata/v4/AdminService/Categories(11)
Content-Type: application/json

### Read Categories

GET http://localhost:8080/odata/v4/AdminService/Categories(10)?$expand=parent
Content-Type: application/json

### Read Categories

GET http://localhost:8080/odata/v4/AdminService/Categories?$expand=children
Content-Type: application/json


